"""
Django settings for glad project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from urllib.parse import urlparse

from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.getenv("ENV_FILE", ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

ENVIRONMENT = os.getenv("ENVIRONMENT", "production")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

if ENVIRONMENT == "production" and DEBUG:
    logging.warning(
        "DEBUG is set to True in production environment. "
        "Please set DEBUG to False for production."
    )

# APP_URL is the canonical public URL of the app (e.g. https://myapp.example.com).
# All URL-derived settings fall back to it; each can still be overridden individually.
_app_url = os.environ.get("APP_URL", "").rstrip("/")
_app_url_parsed = urlparse(_app_url) if _app_url else None
_app_hostname = _app_url_parsed.hostname if _app_url_parsed else None

# Only set ALLOWED_HOSTS if explicitly configured in environment
ALLOWED_HOSTS = (
    [x.strip() for x in os.environ["ALLOWED_HOSTS"].split(",")]
    if os.environ.get("ALLOWED_HOSTS")
    else []
)

# https://github.com/adamchainz/django-cors-headers
_cors_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if _cors_env:
    CORS_ALLOWED_ORIGINS = [x.strip() for x in _cors_env.split(",")]
elif _app_url:
    CORS_ALLOWED_ORIGINS = [_app_url]

# https://docs.djangoproject.com/en/5.0/topics/http/sessions/#settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = bool(
    os.environ.get("SESSION_COOKIE_SECURE", "False").lower() == "true"
)
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 hours max
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Force logout when closing browser/app

# https://docs.djangoproject.com/en/5.0/ref/csrf/#settings
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False").lower() == "true"
_csrf_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    list(filter(None, _csrf_env.split(",")))
    if _csrf_env
    else ([_app_url] if _app_url else [])
)

# Application definition

INSTALLED_APPS = [
    "base.apps.BaseConfig",
    "accounts.apps.AccountsConfig",
    "finance.apps.FinanceConfig",
    "property.apps.PropertyConfig",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party apps
    "djmoney",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.SessionTimeoutMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "glad.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.session_config",
                "property.context_processors.nav_properties",
                "finance.context_processors.nav_accounts",
            ],
        },
    },
]

WSGI_APPLICATION = "glad.wsgi.application"

MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("DB") == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": "prefer",
                "connect_timeout": 10,
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "data" / "glad.db",
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("DEFAULT_LANGUAGE", "fr")

TIME_ZONE = "Europe/Paris"

USE_I18N = True
USE_L10N = True
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
]
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

USE_TZ = False

DEFAULT_CURRENCY = "EUR"

# WebAuthn settings: explicit env vars take priority, then APP_URL, then per-request.
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN") or _app_url or None
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID") or _app_hostname or None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.path.join(os.environ.get("SUB_PATH") or "", "static/")

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


WHITENOISE_ROOT = os.path.join(BASE_DIR, "static", "glad", "root")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security Headers
# https://docs.djangoproject.com/en/6.0/ref/middleware/#http-strict-transport-security
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'",),
        "style-src": ("'self'", "'unsafe-inline'"),
        "img-src": ("'self'", "data:"),
        "font-src": ("'self'",),
        "connect-src": ("'self'",),
    }

# Logging configuration
# https://docs.djangoproject.com/en/5.2/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "stderr": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["stderr"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["stderr"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stderr"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["stderr"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
