"""
Django settings for glad project.

Generated by 'django-admin startproject', maintained for Django 6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
from pathlib import Path
from urllib.parse import urlparse

from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.getenv("ENV_FILE", ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = os.getenv("ENVIRONMENT", "production")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


def _env_bool(name: str, default: bool) -> bool:
    """Read a boolean environment variable (true/1/yes are truthy)."""
    return os.getenv(name, str(default)).strip().lower() in ("true", "1", "yes")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "The SECRET_KEY environment variable is required. "
        "Generate one with: python -c 'from django.core.management.utils "
        "import get_random_secret_key; print(get_random_secret_key())'"
    )

if ENVIRONMENT == "production" and DEBUG:
    logging.getLogger("glad").warning(
        "DEBUG is set to True in production environment. "
        "Please set DEBUG to False for production."
    )

# APP_URL is the canonical public URL of the app (e.g. https://myapp.example.com).
# All URL-derived settings fall back to it; each can still be overridden individually.
_app_url = os.environ.get("APP_URL", "").rstrip("/")
_app_url_parsed = urlparse(_app_url) if _app_url else None
_app_hostname = _app_url_parsed.hostname if _app_url_parsed else None

APP_URL = _app_url
_app_is_https = bool(_app_url_parsed and _app_url_parsed.scheme == "https")

if _app_url:
    USE_X_FORWARDED_HOST = True
    if _app_is_https:
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ALLOWED_HOSTS: explicit list from the environment, else the APP_URL hostname.
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS = [x.strip() for x in os.environ["ALLOWED_HOSTS"].split(",")]
elif _app_hostname:
    ALLOWED_HOSTS = [_app_hostname]
else:
    ALLOWED_HOSTS = []

# HTTPS hardening: defaults follow the APP_URL scheme, each can be overridden.
# The health endpoint stays reachable over plain HTTP for container health checks.
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", _app_is_https and not DEBUG)
SECURE_REDIRECT_EXEMPT = [r"^health$"]

# https://docs.djangoproject.com/en/6.0/topics/http/sessions/#settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", _app_is_https)
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(8 * 60 * 60)))  # seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every activity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Force logout when closing browser/app

# https://docs.djangoproject.com/en/6.0/ref/csrf/#settings
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", _app_is_https)
_csrf_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    list(filter(None, _csrf_env.split(",")))
    if _csrf_env
    else ([_app_url] if _app_url else [])
)

# Application definition

INSTALLED_APPS = [
    "base.apps.BaseConfig",
    "accounts.apps.AccountsConfig",
    "finance.apps.FinanceConfig",
    "property.apps.PropertyConfig",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party apps
    "djmoney",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.SessionTimeoutMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "glad.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.csp",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.session_config",
                "property.context_processors.nav_properties",
                "finance.context_processors.nav_accounts",
            ],
        },
    },
]

WSGI_APPLICATION = "glad.wsgi.application"

MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("DB") == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
            # Persistent connections, validated before reuse.
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "600")),
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "sslmode": os.getenv("DB_SSL_MODE", "prefer"),
                "connect_timeout": 10,
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "data" / "glad.db",
            "OPTIONS": {
                # Write-ahead log allows concurrent readers during writes,
                # busy_timeout waits instead of failing on a locked database.
                "init_command": (
                    "PRAGMA journal_mode=WAL;"
                    "PRAGMA synchronous=NORMAL;"
                    "PRAGMA busy_timeout=5000;"
                    "PRAGMA foreign_keys=ON;"
                ),
                "transaction_mode": "IMMEDIATE",
            },
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"

# Email configuration
EMAIL_HOST = os.getenv("EMAIL_HOST")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    default_use_ssl = EMAIL_PORT == 465
    default_use_tls = EMAIL_PORT == 587
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", str(default_use_tls)).lower() in (
        "true",
        "1",
        "yes",
    )
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", str(default_use_ssl)).lower() in (
        "true",
        "1",
        "yes",
    )
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))  # seconds
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Glad <glad@localhost>")
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[Glad] ")

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.environ.get("DEFAULT_LANGUAGE", "fr")

TIME_ZONE = "Europe/Paris"

USE_I18N = True
LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
]
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

USE_TZ = False

DEFAULT_CURRENCY = "EUR"

# WebAuthn settings: explicit env vars take priority, then APP_URL, then per-request.
WEBAUTHN_ORIGIN = os.getenv("WEBAUTHN_ORIGIN") or _app_url or None
WEBAUTHN_RP_ID = os.getenv("WEBAUTHN_RP_ID") or _app_hostname or None

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.path.join(os.environ.get("SUB_PATH") or "", "static/")

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


WHITENOISE_ROOT = os.path.join(BASE_DIR, "static", "glad", "root")

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security Headers
# https://docs.djangoproject.com/en/6.0/ref/middleware/#http-strict-transport-security
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Content Security Policy (enabled in every environment so violations show up
# during development). Inline scripts must carry nonce="{{ csp_nonce }}".
# https://docs.djangoproject.com/en/6.0/ref/csp/
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.NONCE],
    # Bootstrap, ApexCharts and Leaflet set inline style attributes.
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    # OpenStreetMap tiles for the property map.
    "img-src": [CSP.SELF, "data:", "blob:", "https://*.tile.openstreetmap.org"],
    "font-src": [CSP.SELF],
    "connect-src": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
    "object-src": [CSP.NONE],
}

# Logging configuration
# https://docs.djangoproject.com/en/6.0/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "stderr": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["stderr"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["stderr"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["stderr"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["stderr"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
