services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.13-bookworm
    volumes:
      - .:/workspace
    command: sleep infinity
    userns_mode: "keep-id"

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace
    command: sleep infinity
    userns_mode: "keep-id"
