# Generated by Django 5.2 on 2025-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentaccount",
            name="cash_balances",
            field=models.ManyToManyField(
                blank=True, to="finance.investmentaccountcash"
            ),
        ),
        migrations.AlterField(
            model_name="investmentaccount",
            name="deposits",
            field=models.ManyToManyField(
                blank=True, to="finance.investmentaccountdeposit"
            ),
        ),
        migrations.AlterField(
            model_name="savingaccount",
            name="balances",
            field=models.ManyToManyField(blank=True, to="finance.savingaccountbalance"),
        ),
        migrations.AlterField(
            model_name="savingaccount",
            name="deposits",
            field=models.ManyToManyField(blank=True, to="finance.savingaccountdeposit"),
        ),
    ]
