# Generated by Django 5.2 on 2025-05-02 14:00

from django.db import migrations


def add_account_types(apps, schema_editor):
    AccountType = apps.get_model("finance", "AccountType")
    AccountType.objects.bulk_create(
        [
            # France
            AccountType(name="Compte Courant", category="CH", country="FR"),
            AccountType(name="Livret A", code="LA", category="SA", country="FR"),
            AccountType(name="Livret Jeune", code="LJ", category="SA", country="FR"),
            AccountType(
                name="Livret Developpement Durable et Solidaire",
                code="LDDS",
                category="SA",
                country="FR",
            ),
            AccountType(
                name="Plan Épargne en Actions", code="PEA", category="IN", country="FR"
            ),
            AccountType(name="Assurance Vie", code="AV", category="IN", country="FR"),
            # USA
            AccountType(name="Checking Account", category="CH", country="US"),
            AccountType(name="Roth IRA", category="SA", country="US"),
            AccountType(name="401(k)", category="IN", country="US"),
            AccountType(name="Traditional IRA", category="SA", country="US"),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_account_types),
    ]
