# Generated by Django 5.2 on 2025-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentaccountholding",
            name="initial_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentaccountholdinghistory",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Quantity of the holding at the moment of valuation",
                max_digits=10,
                null=True,
            ),
        ),
    ]
