# Generated by Django 6.0.6 on 2026-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentaccountholding",
            name="initial_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentaccountholdinghistory",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Quantity of the holding at the moment of valuation",
                max_digits=16,
                null=True,
            ),
        ),
    ]
