# Generated by Django 5.2 on 2025-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_investmentaccountholding_initial_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentaccountdeposit",
            name="update_account_cash",
            field=models.BooleanField(
                default=True,
                help_text="Add this deposit amount to the account cash value",
            ),
        ),
        migrations.AddField(
            model_name="investmentaccountholdinghistory",
            name="subtract_from_cash",
            field=models.BooleanField(
                default=False,
                help_text="Subtract the purchase value from the account cash when saving this holding value",
            ),
        ),
        migrations.AddField(
            model_name="savingaccountdeposit",
            name="update_account_value",
            field=models.BooleanField(
                default=True, help_text="Add this deposit amount to the account value"
            ),
        ),
    ]
