# Generated by Django 5.2 on 2025-06-10 19:31

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_investmentaccount_cash_balances_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentaccountholdinghistory",
            options={"verbose_name_plural": "Investment Account Holding Histories"},
        ),
        migrations.RemoveField(
            model_name="investmentaccountholdinghistory",
            name="fees",
        ),
        migrations.RemoveField(
            model_name="investmentaccountholdinghistory",
            name="fees_currency",
        ),
        migrations.AlterField(
            model_name="investmentaccountholdinghistory",
            name="value",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Value of the holding share at the moment of valuation",
                max_digits=10,
            ),
        ),
    ]
