# Generated by Django 5.2 on 2025-05-02 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_accounttype_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="account",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="accountbalance",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="accountbalance",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="accounttype",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="accounttype",
            name="updated_by",
        ),
    ]
