# Generated by Django 5.2 on 2025-05-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_remove_account_created_by_remove_account_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="balance",
            new_name="initial_balance",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="balance_currency",
            new_name="initial_balance_currency",
        ),
    ]
