# Generated by Django 6.1 on 2026-09-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_other_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccountholding',
            name='asset_class',
            field=models.CharField(blank=True, choices=[('cash', 'Cash and savings books'), ('euro_fund', 'Euro funds'), ('money_market', 'Money market'), ('bonds', 'Bonds'), ('equities', 'Equities'), ('mixed', 'Diversified funds'), ('real_estate', 'Real estate'), ('commodities', 'Commodities and precious metals'), ('crypto', 'Crypto-assets'), ('private_equity', 'Unlisted shares'), ('tangible', 'Tangible assets'), ('other', 'Other')], default='', help_text='Main exposure of the holding, used for the allocation.', max_length=20, verbose_name='Asset class'),
        ),
    ]
