# Generated by Django 6.1 on 2026-09-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_investmentaccountholding_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroFundRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate net of management fees, before social charges.', max_digits=5, verbose_name='Credited rate (%)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='euro_fund_rates', to='finance.investmentaccountholding')),
            ],
            options={
                'verbose_name': 'euro fund rate',
                'verbose_name_plural': 'euro fund rates',
                'ordering': ['holding', '-year'],
                'constraints': [models.UniqueConstraint(fields=('holding', 'year'), name='unique_euro_fund_rate_year')],
            },
        ),
    ]
