# Generated by Django 5.2.7 on 2025-10-31 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "finance",
            "0004_remove_investmentaccountholdinghistory_subtract_from_cash_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentaccountholdinghistory",
            options={
                "ordering": ["-valuation_date", "holding"],
                "verbose_name": "history of holding",
                "verbose_name_plural": "history of holdings",
            },
        ),
        migrations.AlterModelOptions(
            name="savingaccountvalue",
            options={
                "ordering": ["account", "-value_date"],
                "verbose_name": "saving account value",
                "verbose_name_plural": "History of saving accounts",
            },
        ),
    ]
