# Generated by Django 5.2 on 2025-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_rename_balance_account_initial_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="institution",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
