# Generated by Django 5.2.7 on 2025-11-01 00:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_investmentaccountholdinghistory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingaccountdeposit",
            name="deposit_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="savingaccountvalue",
            name="value_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
