# Generated by Django 5.2 on 2025-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_account_description_account_institution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="description",
        ),
        migrations.AddField(
            model_name="account",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
    ]
