# Generated by Django 6.0.5 on 2026-05-31 00:55

import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_savingaccountdeposit_deposit_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentaccount",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Mark this account as a favorite for quick access in the navigation menu.",
                verbose_name="Favorite",
            ),
        ),
        migrations.AddField(
            model_name="savingaccount",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Mark this account as a favorite for quick access in the navigation menu.",
                verbose_name="Favorite",
            ),
        ),
        migrations.AlterField(
            model_name="investmentaccountdeposit",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                help_text="Use a negative value to record a withdrawal",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="savingaccountdeposit",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=djmoney.money.Money(0, "EUR"),
                help_text="Use a negative value to record a withdrawal",
                max_digits=10,
            ),
        ),
    ]
