# Generated by Django 6.1 on 2026-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_ownership_from_remaining_owner_text"),
        ("finance", "0006_investmentaccount_benchmark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investmentaccount",
            options={
                "ordering": ["account_type", "name", "institution"],
                "verbose_name": "investment account",
                "verbose_name_plural": "investment accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="savingaccount",
            options={
                "ordering": ["account_type", "name", "institution"],
                "verbose_name": "saving account",
                "verbose_name_plural": "saving accounts",
            },
        ),
        migrations.RemoveIndex(
            model_name="investmentaccount",
            name="finance_inv_account_f79d2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="savingaccount",
            name="finance_sav_account_be0e9f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="investmentaccount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="savingaccount",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="otherasset",
            name="owner",
        ),
        migrations.AddIndex(
            model_name="investmentaccount",
            index=models.Index(
                fields=["account_type", "name", "institution"],
                name="finance_inv_account_967271_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savingaccount",
            index=models.Index(
                fields=["account_type", "name", "institution"],
                name="finance_sav_account_8d564d_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="investmentaccount",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="savingaccount",
            name="owner",
        ),
    ]
