# Generated by Django 6.0.6 on 2026-06-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notify_on_login",
            field=models.BooleanField(
                default=True,
                help_text="Receive an email notification when you log in.",
                verbose_name="Notify on login",
            ),
        ),
    ]
