# Generated by Django 6.0.6 on 2026-08-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_notify_on_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="live_data_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Fetch real-time market data from Yahoo Finance for holdings "
                    "and ISIN autofill. Disable to avoid external network calls."
                ),
                verbose_name="Enable live market data",
            ),
        ),
    ]
