# Generated by Django 6.1 on 2026-09-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_live_data_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usual household spending per month, used to size the emergency fund.', max_digits=10, null=True, verbose_name='Monthly expenses'),
        ),
    ]
