# Generated by Django 6.1 on 2026-09-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_monthly_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Used to value a life usufruct (article 669 CGI).', null=True, verbose_name='Birth date'),
        ),
    ]
