# Generated by Django 6.0.3 on 2026-03-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_app_lock_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="app_lock_enabled",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="session_timeout",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Auto-logout after this many minutes of inactivity. Default: 30 minutes.",
                verbose_name="Session timeout (minutes)",
            ),
        ),
    ]
