# Generated by Django 6.1 on 2026-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_userprofile_birth_date"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[],
            options={
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_child",
            field=models.BooleanField(
                default=False,
                help_text="A child is a household member who cannot log in.",
                verbose_name="Child",
            ),
        ),
    ]
