# Generated by Django 6.0.3 on 2026-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_userprofile_app_lock_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="session_timeout",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Auto-logout after this many minutes of inactivity. Default: 15 minutes.",
                verbose_name="Session timeout (minutes)",
            ),
        ),
    ]
