# Generated by Django 6.1 on 2026-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndexValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.CharField(choices=[('irl', 'Rent reference index (IRL)'), ('cpi', 'Consumer price index')], max_length=10)),
                ('period', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('published_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'economic index value',
                'verbose_name_plural': 'economic index values',
                'ordering': ['index', '-period'],
                'constraints': [models.UniqueConstraint(fields=('index', 'period'), name='unique_economic_index_period')],
            },
        ),
    ]
