# Generated by Django 6.1 on 2026-09-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_economic_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('properties_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('properties_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('scpi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'net worth snapshot',
                'verbose_name_plural': 'net worth snapshots',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('month', 'currency'), name='unique_net_worth_snapshot')],
            },
        ),
    ]
