# Generated by Django 6.1 on 2026-09-30 23:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_net_worth_snapshot'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('share', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Part of the asset held, e.g. 50 for a couple in indivision.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)], verbose_name='Share (%)')),
                ('right', models.CharField(choices=[('full', 'Full ownership'), ('bare', 'Bare ownership (nue-propriété)'), ('usufruct', 'Usufruct (usufruit)')], default='full', max_length=10, verbose_name='Right')),
                ('usufructuary_birth_date', models.DateField(blank=True, help_text='For a life usufruct, valued with the scale of article 669 CGI.', null=True, verbose_name='Usufructuary birth date')),
                ('usufruct_end_date', models.DateField(blank=True, help_text='For a temporary usufruct: 23 % per period of ten years.', null=True, verbose_name='Usufruct end date')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'ownership',
                'verbose_name_plural': 'ownerships',
                'ordering': ['content_type', 'object_id', '-share'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='base_owners_content_dfc6c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'user'), name='unique_ownership_per_user')],
            },
        ),
    ]
