# Generated by Django 5.2 on 2025-05-02 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="property",
            name="updated_by",
        ),
    ]
