# Generated by Django 5.2 on 2025-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_property_shares_count_alter_property_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
