# Generated by Django 6.1 on 2026-08-31 22:04

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_scpi_bare_ownership_theoretical_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="property",
            name="selling_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Selling value",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="shares_count",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Number of shares in the property (if applicable)",
                max_digits=10,
                null=True,
                verbose_name="Shares count",
            ),
        ),
    ]
