# Generated by Django 6.1 on 2026-09-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_alter_property_address_alter_property_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="additional_address",
            field=models.CharField(
                blank=True,
                help_text="Apartment, floor, building, etc.",
                max_length=255,
                null=True,
                verbose_name="Additional address",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_parcel_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Cadastral parcel number",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cadastral_section",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Cadastral section"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(
                blank=True,
                default="France",
                max_length=100,
                null=True,
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="insee_code",
            field=models.CharField(
                blank=True,
                help_text="French municipality (commune) code.",
                max_length=5,
                null=True,
                verbose_name="INSEE code",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Postal code"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="street_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street name"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="street_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Street number"
            ),
        ),
        migrations.AddField(
            model_name="propertyvalue",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("dvf_estimate", "DVF estimate")],
                default="manual",
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
