# Generated by Django 5.2 on 2025-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_propertyloan"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyloan",
            name="insurance_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Insurance Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="propertyloan",
            name="lender",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lender"
            ),
        ),
    ]
