# Generated by Django 6.0.3 on 2026-03-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_propertyloan_insurance_rate_propertyloan_lender"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyexpense",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date for recurring expenses (leave empty for indefinite)",
                null=True,
                verbose_name="Recurrence end date",
            ),
        ),
        migrations.AddField(
            model_name="propertyexpense",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=20,
                verbose_name="Recurrence type",
            ),
        ),
        migrations.AddField(
            model_name="propertyrevenue",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date for recurring revenues (leave empty for indefinite)",
                null=True,
                verbose_name="Recurrence end date",
            ),
        ),
        migrations.AddField(
            model_name="propertyrevenue",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=20,
                verbose_name="Recurrence type",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="expense_date",
            field=models.DateField(
                help_text="Date of the expense (or start date for recurring expenses)",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="propertyrevenue",
            name="revenue_date",
            field=models.DateField(
                help_text="Date of the revenue (or start date for recurring revenues)",
                verbose_name="Date",
            ),
        ),
    ]
