# Generated by Django 6.0.3 on 2026-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_propertyexpense_recurrence_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyexpense",
            name="recurrence_start_date",
        ),
        migrations.RemoveField(
            model_name="propertyrevenue",
            name="recurrence_start_date",
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="expense_date",
            field=models.DateField(
                help_text="Date of the expense (or start date for recurring expenses)",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="propertyrevenue",
            name="revenue_date",
            field=models.DateField(
                help_text="Date of the revenue (or start date for recurring revenues)",
                verbose_name="Date",
            ),
        ),
    ]
