# Generated by Django 6.1 on 2026-09-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyloan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
