# Generated by Django 6.1 on 2026-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertyloan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_surface',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual built surface, used for DVF estimation.', max_digits=7, null=True, verbose_name='Total surface (m²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carrez law surface area.', max_digits=7, null=True, verbose_name='Floor area (m²)'),
        ),
    ]
