# Generated by Django 6.1 on 2026-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_add_total_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lmnp_start_date',
            field=models.DateField(blank=True, help_text='Start of the furnished rental activity under the régime réel (registration date, or 1 January of the year you switched from micro-BIC). Amortization and the first fiscal year start on the later of this date and the buying date. Leave empty to use the buying date.', null=True, verbose_name='LMNP activity start date'),
        ),
    ]
