# Generated by Django 6.0.3 on 2026-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_propertyloanschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="number_of_rooms",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Number of rooms"
            ),
        ),
    ]
