# Generated by Django 6.0.3 on 2026-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0010_property_number_of_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyloan",
            name="insurance_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Insurance Rate",
            ),
        ),
        migrations.AlterField(
            model_name="propertyloan",
            name="interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Interest Rate",
            ),
        ),
    ]
