# Generated by Django 6.1 on 2026-09-17 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_ledger_accounting_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LmnpDeclarationSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Fiscal year')),
                ('rules_version', models.CharField(help_text='Year of the tax rule set used for the computation.', max_length=8, verbose_name='Rules version')),
                ('property_names', models.JSONField(default=list, help_text='Names of the properties at the time of the snapshot.', verbose_name='Property names')),
                ('data', models.JSONField(verbose_name='Frozen data')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lmnp_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('properties', models.ManyToManyField(related_name='lmnp_snapshots', to='property.property', verbose_name='Properties')),
            ],
            options={
                'verbose_name': 'LMNP declaration snapshot',
                'verbose_name_plural': 'LMNP declaration snapshots',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
    ]
