# Generated by Django 6.0.3 on 2026-04-17 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_alter_propertyloan_insurance_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyloan",
            name="insurance_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=5,
                verbose_name="Insurance Rate",
            ),
        ),
        migrations.AlterField(
            model_name="propertyloan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=5,
                verbose_name="Interest Rate",
            ),
        ),
    ]
