# Generated by Django 6.1 on 2026-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_lmnp_declaration_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyledgerentryexception',
            name='actual_date',
            field=models.DateField(blank=True, help_text='Actual transfer date, when it differs from the planned date.', null=True, verbose_name='Actual date'),
        ),
        migrations.AddField(
            model_name='propertyledgerentryexception',
            name='is_checked',
            field=models.BooleanField(default=False, help_text='The planned transfer has been verified on the bank account.', verbose_name='Is checked'),
        ),
    ]
