# Generated by Django 6.1 on 2026-09-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_ledger_exception_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dpe_date',
            field=models.DateField(blank=True, help_text='Date the energy performance diagnosis was carried out.', null=True, verbose_name='DPE date'),
        ),
        migrations.AddField(
            model_name='property',
            name='dpe_rating',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='', max_length=1, verbose_name='Energy rating (DPE)'),
        ),
    ]
