# Generated by Django 6.0.3 on 2026-04-18 09:27

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        (
            "property",
            "0013_remove_propertyledgerentry_property_pr_propert_e17344_idx_and_more",
        ),
        ("property", "0014_remove_propertyledgerentry_mandate"),
        ("property", "0015_remove_managementmandate_manager_and_more"),
        ("property", "0016_remove_tenant_leasetenant_irl_fields"),
        ("property", "0017_remove_lease_tenant_email_and_more"),
        ("property", "0018_alter_property_buying_value_gross"),
    ]

    dependencies = [
        ("property", "0012_alter_propertyloan_insurance_rate_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="propertyledgerentry",
            name="property_pr_propert_e17344_idx",
        ),
        migrations.AlterField(
            model_name="propertyledgerentry",
            name="management_category",
            field=models.CharField(
                choices=[
                    ("rent_collected", "Rent collected"),
                    ("charges_collected", "Charges collected"),
                    ("other_income", "Other income"),
                    ("deposit_in", "Deposit received"),
                    ("manager_reversal", "Manager reversal"),
                    ("management_fees", "Management fees"),
                    ("other_general_fees", "Other general fees"),
                    ("coownership", "Co-ownership fees"),
                    ("maintenance", "Routine maintenance"),
                    ("works", "Works"),
                    ("insurance", "Insurance"),
                    ("property_tax", "Property tax"),
                    ("cfe", "CFE"),
                    ("misc_deductible", "Miscellaneous deductible"),
                    ("loan_interest", "Loan interest"),
                    ("loan_insurance", "Loan insurance"),
                    ("loan_repayment", "Loan capital repayment"),
                    ("deposit_out", "Deposit returned"),
                    ("non_deductible", "Other non-deductible"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyledgerentry",
            index=models.Index(
                fields=["property", "management_category"],
                name="property_pr_propert_428547_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="propertyledgerentry",
            name="tax_category",
        ),
        migrations.RemoveField(
            model_name="propertyledgerentry",
            name="mandate",
        ),
        migrations.RemoveField(
            model_name="managementmandate",
            name="manager",
        ),
        migrations.AddField(
            model_name="managementmandate",
            name="manager_address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="managementmandate",
            name="manager_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="managementmandate",
            name="manager_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Manager name"
            ),
        ),
        migrations.AddField(
            model_name="managementmandate",
            name="manager_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Phone"),
        ),
        migrations.DeleteModel(
            name="PropertyManager",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="tenants",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="irl_indexed",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="irl_reference_quarter",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="irl_reference_value",
        ),
        migrations.DeleteModel(
            name="LeaseTenant",
        ),
        migrations.DeleteModel(
            name="Tenant",
        ),
        migrations.AddField(
            model_name="lease",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="lease",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="last_name",
            field=models.CharField(
                default="Unknown name", max_length=100, verbose_name="Last name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lease",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="property",
            name="buying_value_gross",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=0,
                help_text="The gross value of the property at the time of purchase, including notary fees for example.",
                max_digits=10,
                null=True,
                verbose_name="Gross Buying Value",
            ),
        ),
    ]
