# Generated by Django 6.1 on 2026-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_property_dpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='irl_reference_quarter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], help_text='Quarter of the rent reference index named in the lease, usually the last one published when it was signed.', null=True, verbose_name='IRL reference quarter'),
        ),
        migrations.AddField(
            model_name='lease',
            name='irl_reference_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='IRL value of the current rent (at signing or last revision).', max_digits=7, null=True, verbose_name='IRL reference value'),
        ),
        migrations.AddField(
            model_name='lease',
            name='last_rent_revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last rent revision'),
        ),
    ]
