# Generated by Django 6.1 on 2026-10-03 19:05

import calendar
import datetime

from django.db import migrations, models


def _add_months(day: datetime.date, months: int) -> datetime.date:
    """Add months to a date, clamped to the last day of the target month."""
    total = day.year * 12 + day.month - 1 + months
    year, month = divmod(total, 12)
    month += 1
    return datetime.date(year, month, min(day.day, calendar.monthrange(year, month)[1]))


def _months_between(start: datetime.date, end: datetime.date) -> int:
    return (end.year - start.year) * 12 + end.month - start.month


def end_on_last_installment(apps, schema_editor):
    """Move the end date of the loans with a first payment date to their last one.

    The form used to set ``end_date = start_date + duration`` whatever the first
    payment date, while the end date now is the date of the last installment.
    Loans without a first payment date already end there.
    """
    loan_model = apps.get_model("property", "PropertyLoan")
    loans = loan_model.objects.filter(first_payment_date__isnull=False).only(
        "start_date", "end_date", "first_payment_date"
    )
    for loan in loans:
        duration = _months_between(loan.start_date, loan.end_date)
        if duration > 0:
            loan_model.objects.filter(pk=loan.pk).update(
                end_date=_add_months(loan.first_payment_date, duration - 1)
            )


def end_after_duration(apps, schema_editor):
    """Restore ``end_date = start_date + duration`` (reverse migration)."""
    loan_model = apps.get_model("property", "PropertyLoan")
    loans = loan_model.objects.filter(first_payment_date__isnull=False).only(
        "start_date", "end_date", "first_payment_date"
    )
    for loan in loans:
        duration = _months_between(loan.first_payment_date, loan.end_date) + 1
        if duration > 0:
            loan_model.objects.filter(pk=loan.pk).update(
                end_date=_add_months(loan.start_date, duration)
            )


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_lease_irl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyloan",
            name="first_payment_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the first bank debit, one month after the start date when empty. When it falls on another day, the interest of the first installment covers the actual number of days, as banks do.",
                null=True,
                verbose_name="First payment date",
            ),
        ),
        migrations.RunPython(
            end_on_last_installment, end_after_duration, elidable=True
        ),
    ]
