# Generated by Django 6.0.4 on 2026-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0014_amortizationasset_squashed_0015_alter_amortizationasset_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="amortizationasset",
            name="cerfa_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("terrains", "Terrains"),
                    ("constructions", "Constructions"),
                    ("installations", "Installations générales"),
                    ("autres", "Autres immobilisations corporelles"),
                ],
                default="",
                help_text="Asset category for cerfa 2033-C: terrains, constructions, installations générales, or autres immobilisations corporelles.",
                max_length=20,
                verbose_name="Cerfa 2033-C category",
            ),
        ),
    ]
