# Generated by Django 6.0.4 on 2026-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0017_add_purchase_fees_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="coproperty_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Share of the coproperty (in %), if applicable.",
                max_digits=5,
                null=True,
                verbose_name="Coproperty share (%)",
            ),
        ),
    ]
