# Generated by Django 6.0.4 on 2026-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0020_alter_propertyledgerentry_management_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyledgerentry",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("biannual", "Biannual"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=20,
                verbose_name="Recurrence type",
            ),
        ),
    ]
