# Generated by Django 6.0.4 on 2026-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_propertyledgerentry_recurrence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyledgerentry',
            name='management_category',
            field=models.CharField(choices=[('rent_collected', 'Rent collected'), ('charges_collected', 'Charges collected'), ('other_income', 'Other income'), ('deposit_in', 'Deposit received'), ('manager_reversal', 'Manager reversal'), ('management_fees', 'Management fees'), ('letting_fees', 'Letting fees'), ('other_general_fees', 'Other general fees'), ('coownership', 'Co-ownership fees'), ('maintenance', 'Routine maintenance'), ('works', 'Works'), ('insurance', 'Insurance'), ('property_tax', 'Property tax'), ('cfe', 'CFE'), ('misc_deductible', 'Miscellaneous deductible'), ('loan_interest', 'Loan interest'), ('loan_insurance', 'Loan insurance'), ('rental_guarantee', 'Rental guarantee'), ('loan_repayment', 'Loan capital repayment'), ('deposit_out', 'Deposit returned'), ('non_deductible', 'Other non-deductible'), ('other', 'Other')], max_length=30, verbose_name='Category'),
        ),
    ]
