# Generated by Django 6.0.4 on 2026-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0022_alter_propertyledgerentry_management_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="amortizationasset",
            name="property_am_propert_9f825a_idx",
        ),
        migrations.RenameField(
            model_name="amortizationasset",
            old_name="acquisition_date",
            new_name="beginning_date",
        ),
        migrations.AddIndex(
            model_name="amortizationasset",
            index=models.Index(
                fields=["property", "beginning_date"],
                name="property_am_propert_53b341_idx",
            ),
        ),
        migrations.AlterField(
            model_name="amortizationasset",
            name="beginning_date",
            field=models.DateField(
                help_text="Date of the beginning of the asset's useful life.",
                verbose_name="Beginning date",
            ),
        ),
    ]
