# Generated by Django 6.0.4 on 2026-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0023_remove_amortizationasset_property_am_propert_9f825a_idx_and_more_squashed_0024_alter_amortizationasset_beginning_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="amortizationasset",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional free-text notes about this asset.",
                verbose_name="Notes",
            ),
        ),
    ]
