# Generated by Django 6.0.4 on 2026-05-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0025_amortizationasset_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="amortizationasset",
            name="source_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Ledger entry recording the payment for this asset. If set, this transaction is excluded from deductible charges to avoid double-counting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capitalized_as",
                to="property.propertyledgerentry",
                verbose_name="Source transaction",
            ),
        ),
    ]
