# Generated by Django 6.0.4 on 2026-05-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0026_amortizationasset_source_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amortizationasset",
            name="source_transaction",
        ),
        migrations.AddField(
            model_name="amortizationasset",
            name="source_transactions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ledger entries recording the payment(s) for this asset. Linked transactions are excluded from deductible charges to avoid double-counting.",
                related_name="capitalized_as",
                to="property.propertyledgerentry",
                verbose_name="Source transactions",
            ),
        ),
    ]
