# Generated by Django 6.0.4 on 2026-05-05 22:48

from django.db import migrations, models


def migrate_other_to_non_deductible(apps, schema_editor):
    PropertyLedgerEntry = apps.get_model("property", "PropertyLedgerEntry")
    PropertyLedgerEntry.objects.filter(management_category="other").update(
        management_category="non_deductible"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0029_loan_bank_reference_annual_statement"),
    ]

    operations = [
        migrations.RunPython(
            migrate_other_to_non_deductible,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="property",
            name="buying_date",
            field=models.DateField(
                help_text="Date of purchase of the property on the notary deed.",
                verbose_name="Buying Date",
            ),
        ),
        migrations.AlterField(
            model_name="propertyledgerentry",
            name="management_category",
            field=models.CharField(
                choices=[
                    ("rent_collected", "Rent collected"),
                    ("charges_collected", "Charges collected"),
                    ("other_income", "Other income"),
                    ("deposit_in", "Deposit received"),
                    ("manager_reversal", "Manager reversal"),
                    ("management_fees", "Management fees"),
                    ("letting_fees", "Letting fees"),
                    ("other_general_fees", "Other general fees"),
                    ("coownership", "Co-ownership fees"),
                    ("maintenance", "Routine maintenance"),
                    ("works", "Works"),
                    ("furnitures", "Furnitures"),
                    ("insurance", "Insurance"),
                    ("property_tax", "Property tax"),
                    ("cfe", "CFE"),
                    ("misc_deductible", "Miscellaneous deductible"),
                    ("loan_interest", "Loan interest"),
                    ("loan_insurance", "Loan insurance"),
                    ("rental_guarantee", "Rental guarantee"),
                    ("loan_repayment", "Loan capital repayment"),
                    ("deposit_out", "Deposit returned"),
                    ("non_deductible", "Other non-deductible"),
                ],
                max_length=30,
                verbose_name="Category",
            ),
        ),
    ]
