# Generated by Django 6.0.4 on 2026-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0030_alter_property_buying_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyloan",
            name="first_payment_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the first bank debit. When set, the first month's interest is calculated proportionally based on the actual number of days between the disbursement date and the first payment, matching the bank's amortization table.",
                null=True,
                verbose_name="First payment date",
            ),
        ),
    ]
