# Generated by Django 6.0.4 on 2026-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0031_add_first_payment_date_to_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyledgerentry",
            name="third_party",
            field=models.CharField(
                blank=True,
                help_text="Optional. Name of the third party (tenant, supplier, etc.).",
                max_length=200,
                verbose_name="Third party",
            ),
        ),
    ]
