# Generated by Django 6.0.5 on 2026-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0032_add_third_party_to_ledger_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amortizationasset",
            name="duration_years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amortization duration in years. Leave blank for non-depreciable assets (e.g. land).",
                null=True,
                verbose_name="Duration (years)",
            ),
        ),
    ]
