# Generated by Django 6.0.5 on 2026-05-11 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0034_add_alur_works_fund_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PropertyLoanAnnualStatement",
        ),
    ]
