# Generated by Django 6.0.5 on 2026-05-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0036_replace_loan_schedule_with_amortization_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Mark this property as a favorite for quick access in the navigation menu.",
                verbose_name="Favorite",
            ),
        ),
    ]
