# Generated by Django 6.0.5 on 2026-05-31 13:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0039_scpi_management_fee_rate_scpi_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scpiinvestment",
            name="unit_purchase_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                help_text="Total price paid per share at subscription (entry fees included).",
                max_digits=12,
                verbose_name="Unit purchase price",
            ),
        ),
    ]
