# Generated by Django 6.0.5 on 2026-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0040_alter_scpiinvestment_unit_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="scpi",
            name="dividend_recurrence",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Annual"),
                ],
                default="annual",
                help_text="How often dividends are paid: monthly, quarterly, or annually.",
                max_length=10,
                verbose_name="Dividend recurrence",
            ),
        ),
    ]
