# Generated by Django 6.0.5 on 2026-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0042_scpidividend_attach_to_fund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scpi",
            name="dividend_recurrence",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Annual"),
                ],
                default="quarterly",
                help_text="How often dividends are paid: monthly, quarterly, or annually.",
                max_length=10,
                verbose_name="Dividend recurrence",
            ),
        ),
    ]
