# Generated by Django 6.0.5 on 2026-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0043_alter_scpi_dividend_recurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="shares_count",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Number of shares in the property (if applicable)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scpiinvestment",
            name="shares_count",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Number of shares held, e.g. 100.0000.",
                max_digits=10,
                verbose_name="Number of shares",
            ),
        ),
    ]
