# Generated by Django 6.0.5 on 2026-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0045_alter_scpi_entry_fee_rate_alter_scpi_exit_fee_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scpiinvestment",
            name="sold_date",
            field=models.DateField(
                blank=True,
                help_text="Date on which all the shares were sold, if applicable.",
                null=True,
                verbose_name="Sold date",
            ),
        ),
    ]
