name: Backend
on:
  push:

jobs:
  tests:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      - name: Install the project
        working-directory: backend
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        working-directory: backend
        run: uvx ruff check

      - name: Run ruff format
        working-directory: backend
        run: uvx ruff format --check

      - name: Run tests
        working-directory: backend
        run: uv run pytest tests
