name: Release

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup | Force correct release branch on workflow sha
        run: git checkout -B ${{ github.ref_name }}

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup | Install Python & Project dependencies
        run: uv sync --extra build

      - name: Release | Semantic Version Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run semantic-release -v version

      - name: Publish | Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.release.outputs.released == 'true' }}
        with:
          packages-dir: dist
          print-hash: true
          verbose: true
